package app.use_case.display_event;

import java.util.ArrayList;

/**
 * Output Data for the Display Event Use Case.
 * This class encapsulates the output data generated by the Display Event use case.
 * It holds a list of event details that are prepared for display on the front end.
 */
public class DisplayEventOutputData {

    private final ArrayList<ArrayList<Object>> events;

    /**
     * Constructs a new {@link DisplayEventOutputData}.
     * @param events A nested {@link ArrayList} containing event details. Each inner
     *               {@link ArrayList} represents the properties of a single event.
     *               Must not be {@code null}.
     */
    public DisplayEventOutputData(ArrayList<ArrayList<Object>> events) {
        this.events = events;
    }

    /**
     * Retrieves the list of event details.
     * @return A nested {@link ArrayList} containing event details. Each inner
     *         {@link ArrayList} represents the properties of a single event.
     */
    public ArrayList<ArrayList<Object>> getEvents() {
        return events;
    }
}
